services:
  bind9:
    image: internetsystemsconsortium/bind9:9.18
    container_name: dns-server
    volumes:
      - ./bind:/etc/bind
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: unless-stopped
